version = 0.1
[default.deploy.parameters]
stack_name = "key-dev"
resolve_s3 = true
s3_prefix = "key-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []


[production.deploy.parameters]
stack_name = "key-prod"
resolve_s3 = true
s3_prefix = "key-prod"
region = "us-east-1"
profile = "key-stackset-deployer"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
