AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition

Parameters:
  RDSMasterUserName:
    Type: String
    Default: admin
  RDSDBName:
    Type: String
    Default: index
  UsersQnTableName:
    Type: String
    Default: trueblocks-qn-users-qn
  AppearancesQueueBatchSize:
    Type: Number
    Default: "10"

# Global values that are applied to all applicable resources in this template
Globals:
  Function:
    MemorySize: 1024
    Architectures: ["x86_64"]
    Timeout: 30
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:38"

Resources:
  ###
  # Databases
  ###

  ## SQL Appearances

  # Database master user password. Note: we want it to be managed by RDS service
  RDSMasterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'RDS instance secret'
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${!Ref RDSMasterUserName}"}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  # Database
  IndexDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: indexdatabase
      Engine: postgres
      DBName: !Ref RDSDBName
      MasterUsername: !Ref RDSMasterUserName
      # https://github.com/aws-samples/aws-secrets-manager-secure-database-credentials/blob/main/secretsmanager_IaC.yml
      # MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSInstanceRotationSecret, ':SecretString:password}}' ]]
      # TODO: Does this rotate the secret?
      ManageMasterUserPassword: true
      MasterUserSecret:
        SecretArn: !Ref RDSMasterSecret
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup

  ### DynamoDB QN users
  UsersQn:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: QuicknodeId
        Type: String
      TableName: !Ref UsersQnTableName

  ###
  # Appearances Queue
  ###

  AppearancesQueueConsume:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: consume
      CodeUri: queue/consume/lambda
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt AppearancesQueue.Arn
            BatchSize: !Ref AppearancesQueueBatchSize
      Environment:
        Variables:
          QNEXT_SQS_BATCHSIZE: !Ref AppearancesQueueBatchSize
          QNEXT_DATABASE_HOST: !GetAtt IndexDatabase.Endpoint.Address
          QNEXT_DATABASEPORT: !GetAtt IndexDatabase.Endpoint.Port
          QNEXT_DATABASE_USER: !Ref RDSMasterUserName
          QNEXT_DATABASE_AWSSECRET: !Ref RDSMasterSecret
          QNEXT_DATABASE_DATABASE: !Ref RDSDBName
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy

  AppearancesQueue:
    Type: AWS::SQS::Queue

  ###
  # API
  ###

  QnAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      # Models:
      #   # {"jsonrpc":"2.0","method":"eth_syncing","params":[], "id": 1}
      #   RPCCall:
      #     type: object
      #     required:
      #       - method
      #       - params
      #     Properties:
      #       jsonrpc:
      #         Type: string
      #       id:
      #         Type: number
      #       method:
      #         Type: string
      #       params:
      #         Type: array
      #         Items:
      #           address:
      #             Type: string

      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt MyAuthFunction.Arn
            Identity:
              Headers:
                - x-quicknode-id

  ### QN healthcheck
  # Make sure this endpoint does not require auth
  ApiHealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: healthcheck
      CodeUri: quicknode/healthcheck/lambda
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /healthcheck
            Method: get
            RestApiId:
              Ref: QnAPI
      Environment:
        Variables:
          QNEXT_DATABASE_HOST: !GetAtt IndexDatabase.Endpoint.Address
          QNEXT_DATABASE_PORT: !GetAtt IndexDatabase.Endpoint.Port
          QNEXT_DATABASE_USER: !Ref RDSMasterUserName
          QNEXT_DATABASE_AWSSECRET: !Ref RDSMasterSecret
          QNEXT_DATABASE_DATABASE: !Ref RDSDBName
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref RDSMasterUserName
        - CloudWatchLambdaInsightsExecutionRolePolicy

  ### QN Provision
  ProvisionQnSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: QN Provision username and password
      SecretString: '{"username":"Placeholder","password":"placeholder"}'

  ApiProvisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: provision
      CodeUri: quicknode/provision/lambda
      Events:
        Provision:
          Type: Api
          Properties:
            Path: /provision
            Method: post
            RestApiId:
              Ref: QnAPI
        Update:
          Type: Api
          Properties:
            Path: /update
            Method: put
            RestApiId:
              Ref: QnAPI
        Deactivate:
          Type: Api
          Properties:
            Path: /deactivate_endpoint
            Method: delete
            RestApiId:
              Ref: QnAPI
        Deprovision:
          Type: Api
          Properties:
            Path: /deprovision
            Method: delete
            RestApiId:
              Ref: QnAPI
      Environment:
        Variables:
          QNEXT_QNPROVISION_AWSSECRET: !Ref ProvisionQnSecret
          QNEXT_QNPROVISION_TABLENAME: !Ref UsersQnTableName
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref ProvisionQnSecret
        - CloudWatchLambdaInsightsExecutionRolePolicy

  ### RPC route
  RpcFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: query
      CodeUri: query/lambda
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /rpc
            Method: post
            # RequestModel
            Auth:
              ApiKeyRequired: true
            RestApiId:
              Ref: QnAPI
      Environment:
        Variables:
          QNEXT_DATABASE_HOST: !GetAtt IndexDatabase.Endpoint.Address
          QNEXT_DATABASE_PORT: !GetAtt IndexDatabase.Endpoint.Port
          QNEXT_DATABASE_USER: !Ref RDSMasterUserName
          QNEXT_DATABASE_AWSSECRET: !Ref RDSMasterSecret
          QNEXT_DATABASE_DATABASE: !Ref RDSDBName
      VpcConfig: # For accessing RDS instance
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref privateLambdaSubnet1
          - !Ref privateLambdaSubnet2
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref RDSMasterSecret
        - CloudWatchLambdaInsightsExecutionRolePolicy

  ###
  # S3 object storage
  ###

  # Not used:
  IndexBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: trueblocks-qn-index

  ###
  # Network
  ###

  # create VPC
  RDSVPC:
    Type: AWS::EC2::VPC
    Properties:
        CidrBlock: 172.32.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true

  # create subnets
  privateDBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RDSVPC
      CidrBlock: 172.32.0.0/20

  privateDBSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RDSVPC
      CidrBlock: 172.32.16.0/20

  privateLambdaSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RDSVPC
      CidrBlock: 172.32.32.0/20

  privateLambdaSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RDSVPC
      CidrBlock: 172.32.48.0/20

  RDSSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "description"
      SubnetIds:
        - !Ref privateDBSubnet1
        - !Ref privateDBSubnet2

  # Security groups
  # https://repost.aws/knowledge-center/connect-lambda-to-an-rds-instance

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Postgres access from lambda subnets
      VpcId: !Ref RDSVPC
      # Make sure the database is only accessible from the stack, database port only
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId : !Ref LambdaSecurityGroup

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda ENIs
      VpcId: !Ref RDSVPC
      # Allow lambdas to connect to the database
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: -1
          ToPort: 5432
          DestinationSecurityGroupId: !Ref RDSSecurityGroup
