AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition

# Global values that are applied to all applicable resources in this template
Globals:
  Function:
    MemorySize: 256
    Architectures: ["x86_64"]
    Timeout: 60
    Environment:
      Variables:
        SCNR_BUCKET_NAME: trueblocks-qn-index #!Ref IndexBucket

Resources:
  # API
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  # Adds a GET api endpoint at "/index" to the ApiGatewayApi via an Api event
  ApiFunction:
    Type: AWS::Serverless::Function
    DependsOn: "MountTarget1"
    Properties:
      Runtime: go1.x
      Handler: scanner
      CodeUri: scanner/lambda
      Layers:
        # move to Globals to enable for all functions
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:38"
      VpcConfig:
        SecurityGroupIds:
        - Ref: EfsSecurityGroup
        SubnetIds:
        - Ref: Subnet1
      FileSystemConfigs:
      - Arn: !GetAtt AccessPoint.Arn
        LocalMountPath: "/mnt/efs"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /index
            Method: get
            RequestParameters:
              - method.request.querystring.address:
                  Required: true
                  Caching: false
            TimeoutInMillis: 29000
            Auth:
              ApiKeyRequired: true
            RestApiId:
              Ref: ApiGatewayApi
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref IndexBucket
        - CloudWatchLambdaInsightsExecutionRolePolicy
  # EFS
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-west-2a"
  EfsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: "mnt target sg"
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: "0.0.0.0/0"
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
  AccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId:
        Ref: FileSystem
      PosixUser:
        Uid: "1001"
        Gid: "1001"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1001"
          OwnerUid: "1001"
          Permissions: "755"
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: FileSystem
      SubnetId:
        Ref: Subnet1
      SecurityGroups:
      - Ref: EfsSecurityGroup
  # end EFS
  IndexBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: trueblocks-qn-index
