version: '3.1'

services:

  listener:
    build:
      context: ../..
      dockerfile: queue/insert/Dockerfile
    healthcheck:
      test: pgrep go
    env_file: .env
    restart: always
    ports:
      - 5555:5555

  ipfs:
    image: ipfs/kubo:latest
    healthcheck:
      test: [ "CMD-SHELL", "" ]
    ports:
      - 5001:5001

  core:
    image: dszlachta/trueblocks-core:develop
    ports:
      - "8080:${SERVE_PORT-8080}"
    depends_on:
      listener:
        condition: service_healthy
      ipfs:
        condition: service_healthy
    restart: always
    env_file: .env
    entrypoint: sh /src/core.entrypoint.sh
    volumes:
      - .:/src
      # - cache:/cache
      # - unchained:/unchained
      - ~/key_insert/cache:/cache
      - ~/key_insert/cache/unchained:/unchained

# volumes:
#   unchained:
#     external: true
#   cache:
#     external: true
