AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy stack set

Resources:
  KeyStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Ref AWS::StackName
      PermissionModel: SERVICE_MANAGED
      CallAs: DELEGATED_ADMIN
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      Capabilities:
        - CAPABILITY_AUTO_EXPAND
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
      TemplateURL: ../cloudformation/template.json
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
            - ou-tlap-1pemr15f
            AccountFilterType: INTERSECTION
            Accounts:
              - 088400149162 # Production
              # - 339712865207 # Staging
          Regions:
            - !Ref AWS::Region