AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy stack set

Resources:
  KeyStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Sub ${AWS::StackName}-stackset
      PermissionModel: SERVICE_MANAGED
      CallAs: DELEGATED_ADMIN
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      Capabilities:
        - CAPABILITY_AUTO_EXPAND
        - CAPABILITY_IAM
      TemplateURL: ../cf_template.json
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
            - ou-tlap-1pemr15f
          Regions:
            - !Ref AWS::Region