version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: index
      POSTGRES_PASSWORD: example
    volumes:
      - import:/import
      - db_data:/var/lib/postgresql/data
      - export:/export
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
  import:
  export:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /tmp
