name: Deploy Hugo Site

on:
  push:
    branches:
      - testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo Site
      run: hugo --source ./website

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NEW_SERVER_HOST }}
        username: ${{ secrets.DOCS_USER }}
        key: ${{ secrets.DOCS_PRIVATE_KEY }}
        script: |
          cd /path/to/your/hugo/site/directory
          git pull origin main
          hugo --source ./website
          # Optional: sudo systemctl restart nginx
